#!/bin/bash
# Product Searcher — birinchi marta sozlash skripti

set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

echo "==> Product Searcher setup"
echo "    Papka: $PROJECT_DIR"
echo ""

# .env yaratish
if [ -f .env ]; then
  echo "⚠️  .env allaqachon mavjud. O'zgartirmasdan davom etiladi."
else
  SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(50))" 2>/dev/null || openssl rand -base64 48 | tr -d '/+=' | head -c 50)

  cat > .env << EOF
# Auto-generated by scripts/setup.sh
SECRET_KEY=${SECRET_KEY}
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1,web,0.0.0.0

POSTGRES_DB=product_searcher
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_HOST=db
POSTGRES_PORT=5432

CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

# @BotFather dan oling: https://t.me/BotFather
TELEGRAM_BOT_TOKEN=your-telegram-bot-token-here
BACKEND_URL=http://web:8000

CONFIDENCE_HIGH=0.85
CONFIDENCE_MEDIUM=0.70
SEARCH_TOP_K=5

CLIP_MODEL=ViT-B-32
CLIP_PRETRAINED=openai
EOF

  echo "✅ .env yaratildi"
fi

chmod +x entrypoint.sh 2>/dev/null || true

echo ""
echo "Keyingi qadam:"
echo "  1. .env faylida TELEGRAM_BOT_TOKEN ni to'ldiring (bot kerak bo'lsa)"
echo "  2. Ishga tushiring:  ./scripts/run.sh"
echo "     yoki:            docker compose up --build -d"
echo ""
