# Generated by Django 5.2.16 on 2026-07-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_extra_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Import', 'verbose_name_plural': 'Import'},
        ),
    ]
